# Generated by Django 5.2.9 on 2025-12-08 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('idPelanggan', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('noWa', models.CharField(max_length=20)),
                ('alamat', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('idProduk', models.AutoField(primary_key=True, serialize=False)),
                ('namaProduk', models.CharField(max_length=50)),
                ('ukuranKemasan', models.CharField(max_length=20)),
                ('hargaPerDus', models.PositiveIntegerField()),
                ('stok', models.PositiveIntegerField(default=0)),
                ('deskripsi', models.CharField(blank=True, max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_produk/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sopir',
            fields=[
                ('idSopir', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('noHp', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('idFeedback', models.AutoField(primary_key=True, serialize=False)),
                ('isi', models.TextField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idPelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pelanggan')),
            ],
        ),
        migrations.CreateModel(
            name='Pemesanan',
            fields=[
                ('idPemesanan', models.AutoField(primary_key=True, serialize=False)),
                ('tanggalPemesanan', models.DateTimeField(auto_now_add=True)),
                ('alamatPengiriman', models.CharField(max_length=200)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('buktiBayar', models.ImageField(blank=True, null=True, upload_to='bukti_pembayaran/')),
                ('status', models.CharField(choices=[('Diproses', 'Diproses'), ('Dikirim', 'Dikirim'), ('Selesai', 'Selesai'), ('Dibatalkan', 'Dibatalkan')], default='Diproses', max_length=25)),
                ('fotoPengiriman', models.ImageField(blank=True, null=True, upload_to='bukti_pengiriman/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idPelanggan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pelanggan')),
                ('idSopir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sopir')),
            ],
        ),
        migrations.CreateModel(
            name='Kendarann',
            fields=[
                ('nomorPlat', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('jenis', models.CharField(choices=[('Roda 4', 'Roda 4'), ('Roda 6', 'Roda 6')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idSopir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sopir', verbose_name='Nama Sopir')),
            ],
        ),
        migrations.CreateModel(
            name='StokMasuk',
            fields=[
                ('idStok', models.AutoField(primary_key=True, serialize=False)),
                ('jumlah', models.PositiveIntegerField()),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('keterangan', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idProduk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produk', verbose_name='Nama Produk')),
            ],
        ),
        migrations.CreateModel(
            name='DetailPemesanan',
            fields=[
                ('idDetail', models.AutoField(primary_key=True, serialize=False)),
                ('jumlah', models.PositiveIntegerField()),
                ('subTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('harga_saat_pemesanan', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idPemesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pemesanan')),
                ('idProduk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produk')),
            ],
            options={
                'unique_together': {('idPemesanan', 'idProduk')},
            },
        ),
    ]
