# Generated by Django 5.2.9 on 2025-12-09 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailpemesanan',
            options={'verbose_name': 'Detail Pemesanan', 'verbose_name_plural': 'Detail Pemesanan'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedback'},
        ),
        migrations.AlterModelOptions(
            name='kendarann',
            options={'verbose_name': 'Kendaraan', 'verbose_name_plural': 'Kendaraan'},
        ),
        migrations.AlterModelOptions(
            name='pelanggan',
            options={'verbose_name': 'Pelanggan', 'verbose_name_plural': 'Pelanggan'},
        ),
        migrations.AlterModelOptions(
            name='pemesanan',
            options={'verbose_name': 'Pemesanan', 'verbose_name_plural': 'Pemesanan'},
        ),
        migrations.AlterModelOptions(
            name='produk',
            options={'verbose_name': 'Produk', 'verbose_name_plural': 'Produk'},
        ),
        migrations.AlterModelOptions(
            name='sopir',
            options={'verbose_name': 'Sopir', 'verbose_name_plural': 'Sopir'},
        ),
        migrations.AlterModelOptions(
            name='stokmasuk',
            options={'verbose_name': 'Stok Masuk', 'verbose_name_plural': 'Stok Masuk'},
        ),
        migrations.AlterUniqueTogether(
            name='detailpemesanan',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='kendarann',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='kendarann',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='pelanggan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pelanggan',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='pemesanan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pemesanan',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='produk',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='produk',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='sopir',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sopir',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='stokmasuk',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='stokmasuk',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='detailpemesanan',
            name='idDetail',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID Detail'),
        ),
        migrations.AlterField(
            model_name='detailpemesanan',
            name='idPemesanan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pemesanan', verbose_name='ID Pemesanan'),
        ),
        migrations.AlterField(
            model_name='detailpemesanan',
            name='idProduk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produk', verbose_name='Produk'),
        ),
        migrations.AlterField(
            model_name='detailpemesanan',
            name='jumlah',
            field=models.PositiveIntegerField(verbose_name='Jumlah Pesanan'),
        ),
        migrations.AlterField(
            model_name='detailpemesanan',
            name='subTotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Sub Total'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='idFeedback',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID Feedback'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='idPelanggan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pelanggan', verbose_name='Pelanggan'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='isi',
            field=models.TextField(verbose_name='Isi Feedback'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='tanggal',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Feedback'),
        ),
        migrations.AlterField(
            model_name='kendarann',
            name='idSopir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sopir', verbose_name='Nama Sopir'),
        ),
        migrations.AlterField(
            model_name='kendarann',
            name='jenis',
            field=models.CharField(choices=[('Roda 4', 'Roda 4'), ('Roda 6', 'Roda 6')], default='Roda 4', max_length=15, verbose_name='Jenis Kendaraan'),
        ),
        migrations.AlterField(
            model_name='kendarann',
            name='nama',
            field=models.CharField(max_length=20, verbose_name='Nama Kendaraan'),
        ),
        migrations.AlterField(
            model_name='kendarann',
            name='nomorPlat',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Nomor Plat'),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='alamat',
            field=models.CharField(max_length=200, verbose_name='Alamat Pengiriman'),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='idPelanggan',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID Pelanggan'),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='nama',
            field=models.CharField(max_length=50, verbose_name='Nama Pelanggan'),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='noWa',
            field=models.CharField(max_length=20, verbose_name='Nomor WhatsApp'),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='password',
            field=models.CharField(max_length=150, verbose_name='Password (Hash)'),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='username',
            field=models.CharField(max_length=20, unique=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='alamatPengiriman',
            field=models.CharField(max_length=200, verbose_name='Alamat Pengiriman'),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='buktiBayar',
            field=models.ImageField(blank=True, null=True, upload_to='bukti_pembayaran/', verbose_name='Bukti Pembayaran'),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='fotoPengiriman',
            field=models.ImageField(blank=True, null=True, upload_to='bukti_pengiriman/', verbose_name='Foto Pengiriman'),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='idPelanggan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pelanggan', verbose_name='Pelanggan'),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='idPemesanan',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID Pemesanan'),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='idSopir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sopir', verbose_name='Sopir Pengirim'),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='status',
            field=models.CharField(choices=[('Diproses', 'Diproses'), ('Dikirim', 'Dikirim'), ('Selesai', 'Selesai'), ('Dibatalkan', 'Dibatalkan')], default='Diproses', max_length=25, verbose_name='Status Pemesanan'),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='tanggalPemesanan',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Pemesanan'),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Harga'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='deskripsi',
            field=models.CharField(blank=True, max_length=200, verbose_name='Deskripsi'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto_produk/', verbose_name='Foto Produk'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='hargaPerDus',
            field=models.PositiveIntegerField(verbose_name='Harga per Dus'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='idProduk',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID Produk'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='namaProduk',
            field=models.CharField(max_length=30, verbose_name='Nama Produk'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='stok',
            field=models.PositiveIntegerField(default=0, verbose_name='Stok Saat Ini'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='ukuranKemasan',
            field=models.CharField(max_length=20, verbose_name='Ukuran Kemasan'),
        ),
        migrations.AlterField(
            model_name='sopir',
            name='idSopir',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID Sopir'),
        ),
        migrations.AlterField(
            model_name='sopir',
            name='nama',
            field=models.CharField(max_length=20, verbose_name='Nama Sopir'),
        ),
        migrations.AlterField(
            model_name='sopir',
            name='noHp',
            field=models.CharField(max_length=20, verbose_name='Nomor HP'),
        ),
        migrations.AlterField(
            model_name='sopir',
            name='password',
            field=models.CharField(max_length=150, verbose_name='Password (Hash)'),
        ),
        migrations.AlterField(
            model_name='sopir',
            name='username',
            field=models.CharField(max_length=20, unique=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='stokmasuk',
            name='idProduk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produk', verbose_name='Nama Produk'),
        ),
        migrations.AlterField(
            model_name='stokmasuk',
            name='idStok',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID Stok Masuk'),
        ),
        migrations.AlterField(
            model_name='stokmasuk',
            name='jumlah',
            field=models.PositiveIntegerField(verbose_name='Jumlah Masuk'),
        ),
        migrations.AlterField(
            model_name='stokmasuk',
            name='keterangan',
            field=models.CharField(blank=True, max_length=200, verbose_name='Keterangan'),
        ),
        migrations.AlterField(
            model_name='stokmasuk',
            name='tanggal',
            field=models.DateField(auto_now_add=True, verbose_name='Tanggal Masuk'),
        ),
        migrations.RemoveField(
            model_name='detailpemesanan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='detailpemesanan',
            name='harga_saat_pemesanan',
        ),
        migrations.RemoveField(
            model_name='detailpemesanan',
            name='updated_at',
        ),
    ]
