# Generated by Django 5.2.9 on 2025-12-10 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_detailpemesanan_options_alter_feedback_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kendarann',
            new_name='Kendaraan',
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='alamat',
            field=models.CharField(max_length=200, verbose_name='Alamat'),
        ),
        migrations.AlterField(
            model_name='stokmasuk',
            name='idProduk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produk', verbose_name='Produk'),
        ),
    ]
