# Generated by Django 5.2.9 on 2025-12-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_kendarann_kendaraan_alter_pelanggan_alamat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelanggan',
            name='alamat',
            field=models.CharField(max_length=200, verbose_name='Alamat Tempat Tinggal'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='stok',
            field=models.PositiveIntegerField(verbose_name='Stok Saat Ini'),
        ),
    ]
