# Generated by Django 5.2.9 on 2026-02-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pelanggan_alamat_alter_produk_stok'),
    ]

    operations = [
    ]
