# Generated by Django 5.2.9 on 2026-02-16 15:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20260216_2328'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kabupaten',
            fields=[
                ('idKabupaten', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Kabupaten')),
                ('nama', models.CharField(max_length=100, verbose_name='Kabupaten/Kota')),
            ],
            options={
                'verbose_name': 'Kabupaten',
                'verbose_name_plural': 'Kabupaten',
            },
        ),
        migrations.CreateModel(
            name='Provinsi',
            fields=[
                ('idProvinsi', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Provinsi')),
                ('nama', models.CharField(max_length=100, verbose_name='Provinsi')),
            ],
            options={
                'verbose_name': 'Provinsi',
                'verbose_name_plural': 'Provinsi',
            },
        ),
        migrations.AddField(
            model_name='pemesanan',
            name='keterangan_admin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keterangan Aktivitas Admin'),
        ),
        migrations.AddField(
            model_name='pemesanan',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Waktu Pembaruan Terakhir'),
        ),
        migrations.AddField(
            model_name='pemesanan',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Diperbarui Oleh'),
        ),
        migrations.AddField(
            model_name='produk',
            name='satuan',
            field=models.CharField(choices=[('Dus', 'Dus'), ('Galon', 'Galon')], default='Dus', max_length=10, verbose_name='Satuan Produk'),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='alamat',
            field=models.CharField(max_length=200, verbose_name='Detail Alamat (Blok/No Rumah)'),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='tanggalPemesanan',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tanggal Pemesanan'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='hargaPerDus',
            field=models.PositiveIntegerField(verbose_name='Harga per Satuan (Dus/Galon)'),
        ),
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('idKecamatan', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Kecamatan')),
                ('nama', models.CharField(max_length=100, verbose_name='Kecamatan')),
                ('idKabupaten', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.kabupaten', verbose_name='Kabupaten')),
            ],
            options={
                'verbose_name': 'Kecamatan',
                'verbose_name_plural': 'Kecamatan',
            },
        ),
        migrations.CreateModel(
            name='Kelurahan',
            fields=[
                ('idKelurahan', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Kelurahan')),
                ('nama', models.CharField(max_length=100, verbose_name='Kelurahan/Desa')),
                ('idKecamatan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.kecamatan', verbose_name='Kecamatan')),
            ],
            options={
                'verbose_name': 'Kelurahan',
                'verbose_name_plural': 'Kelurahan',
            },
        ),
        migrations.AddField(
            model_name='pelanggan',
            name='idKelurahan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.kelurahan', verbose_name='Kelurahan/Desa'),
        ),
        migrations.AddField(
            model_name='pemesanan',
            name='idKelurahanPengiriman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.kelurahan', verbose_name='Kelurahan/Desa Tujuan'),
        ),
        migrations.AddField(
            model_name='kabupaten',
            name='idProvinsi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.provinsi', verbose_name='Provinsi'),
        ),
    ]
