# Generated by Django 5.2.9 on 2026-03-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_kabupaten_provinsi_pemesanan_keterangan_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kabupaten',
            name='idProvinsi',
        ),
        migrations.RemoveField(
            model_name='kecamatan',
            name='idKabupaten',
        ),
        migrations.RemoveField(
            model_name='kelurahan',
            name='idKecamatan',
        ),
        migrations.RemoveField(
            model_name='pelanggan',
            name='idKelurahan',
        ),
        migrations.RemoveField(
            model_name='pemesanan',
            name='idKelurahanPengiriman',
        ),
        migrations.AddField(
            model_name='pelanggan',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='pelanggan',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='pemesanan',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude Pengiriman'),
        ),
        migrations.AddField(
            model_name='pemesanan',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude Pengiriman'),
        ),
        migrations.DeleteModel(
            name='Provinsi',
        ),
        migrations.DeleteModel(
            name='Kabupaten',
        ),
        migrations.DeleteModel(
            name='Kecamatan',
        ),
        migrations.DeleteModel(
            name='Kelurahan',
        ),
    ]
