# Generated by Django 5.2.9 on 2026-03-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_kabupaten_idprovinsi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelanggan',
            name='isLangganan',
            field=models.BooleanField(default=False, verbose_name='Pelanggan Langganan'),
        ),
        migrations.AddField(
            model_name='pelanggan',
            name='npwp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NPWP'),
        ),
        migrations.AddField(
            model_name='pemesanan',
            name='jatuhTempo',
            field=models.DateField(blank=True, null=True, verbose_name='Jatuh Tempo'),
        ),
        migrations.AddField(
            model_name='pemesanan',
            name='jenisPembayaran',
            field=models.CharField(choices=[('Transfer', 'Transfer'), ('DP', 'DP (Uang Muka)'), ('Piutang', 'Piutang (Bayar Nanti)')], default='Transfer', max_length=25, verbose_name='Jenis Pembayaran'),
        ),
        migrations.AddField(
            model_name='pemesanan',
            name='nominalDibayar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Nominal Dibayar'),
        ),
        migrations.AddField(
            model_name='pemesanan',
            name='sisaTagihan',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Sisa Tagihan'),
        ),
        migrations.AddField(
            model_name='pemesanan',
            name='statusPembayaran',
            field=models.CharField(choices=[('Belum Bayar', 'Belum Bayar'), ('DP', 'DP (Uang Muka)'), ('Lunas', 'Lunas')], default='Lunas', max_length=25, verbose_name='Status Pembayaran'),
        ),
    ]
