# Generated by Django 5.2.9 on 2026-03-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pelanggan_islangganan_pelanggan_npwp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemesanan',
            name='jenisPembayaran',
            field=models.CharField(choices=[('Transfer', 'Transfer'), ('COD', 'COD (Bayar di Tempat)'), ('Piutang', 'Piutang (Bayar Nanti)')], default='Transfer', max_length=25, verbose_name='Jenis Pembayaran'),
        ),
    ]
