# Generated by Django 5.2.9 on 2026-05-27 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_pemesanan_jenispembayaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemesanan',
            name='idPelanggan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pelanggan', verbose_name='Pelanggan'),
        ),
    ]
