"""
Django settings for viquam project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2*njlzd#f0ujtix9yl8f+b7e!5fgr166ng1lho*=2c-vq&26c%'

# SEBELUM DEMO CLIENT: Ubah DEBUG menjadi False.
# Untuk testing awal dengan teman kerja, diatur ke False agar sesuai standar deploy.
DEBUG = False

# Domain PythonAnywhere gratis untuk username: bluecode2004
ALLOWED_HOSTS = ['bluecode2004.pythonanywhere.com', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'viquam.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'core' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'viquam.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'id-id'

TIME_ZONE = 'Asia/Makassar'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# WAJIB UNTUK DEPLOY: Tempat mengumpulkan semua static files termasuk tema Jazzmin
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# PENGATURAN KEAMANAN (Menjawab warning dari python manage.py check --deploy)
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 Tahun
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom password hasher for plain text storage
PASSWORD_HASHERS = [
    'core.hashers.PlainTextPasswordHasher',  # Our custom plain text hasher (default)
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]

# Login URL setting to avoid 404s on protected views
LOGIN_URL = 'admin:login'

JAZZMIN_SETTINGS = {
    'site_title': 'Viquam ',
    'site_header': 'Viquam',
    'site_brand': 'Viquam ',
    'site_logo_classes': 'img-circle',
    'site_logo_alt': 'Viquam  ',
    'welcome_sign': 'Selamat Datang',
    'copyright': '2023 Viquam ',
    'footer_text': 'Viquam',
    'show_ui_builder': True,
    
     "icons": {
        "auth": "fas fa-users-cog",
        "core": "fas fa-box-open",
        "auth.user": "fas fa-user-shield",
        "auth.group": "fas fa-users",
        "core.Pelanggan": "fa-solid fa-users",
        "core.Produk": "fas fa-box",
        "core.Pemesanan": "fas fa-receipt",
        "core.Sopir": "fas fa-user",
        "core.Kendaraan": "fas fa-car",
        "core.Feedback": "fas fa-comment",
        "core.DetailPemesanan": "fas fa-receipt",
        "core.StokMasuk": "fas fa-box",
        "core.Provinsi": "fas fa-map",
        "core.Kabupaten": "fas fa-map-marked-alt",
        "core.Kecamatan": "fas fa-map-signs",
        "core.Kelurahan": "fas fa-map-pin",
    },

    "order_with_respect_to": [
        "auth", 
        "core.Provinsi",
        "core.Kabupaten",
        "core.Kecamatan",
        "core.Kelurahan",
        "core.Pelanggan",
        "core.Produk",
        "core.StokMasuk",
        "core.Sopir",
        "core.Kendaraan",
        "core.Pemesanan",
        "core.Feedback",
    ],

    "topmenu_links": [
        {
            'name': 'Home',
            'url': 'admin:index',
            'icon': 'fa fa-home',
        },
        {
            'name': 'L. Pelanggan',
            'url': 'admin:laporan-pelanggan',
            'icon': 'fas fa-users',
        },
        {
            'name': 'L. Produk & Stok',
            'url': 'admin:laporan-produk',
            'icon': 'fas fa-box-open',
        },
        {
            'name': 'L. Sopir & Kendaraan',
            'url': 'admin:laporan-sopir-kendaraan',
            'icon': 'fas fa-truck-moving',
        },
        {
            'name': 'L. Pemesanan & Pendapatan',
            'url': 'custom_admin:core_pemesanan_laporan',
            'icon': 'fas fa-money-bill-wave',
        },
        {
            'name': 'L. Feedback',
            'url': 'admin:laporan-feedback',
            'icon': 'fas fa-comments',
        },
    ],
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": "navbar-lightblue",
    "accent": "accent-lightblue",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-light-lightblue",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "simplex",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-outline-info",
        "warning": "btn-outline-warning",
        "danger": "btn-danger",
        "success": "btn-outline-success"
    },
    "actions_sticky_top": True
}